//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbaNews.Resources.Web.Areas.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrontStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EbaNews.Resources.Web.Areas.Home.FrontStrings", typeof(FrontStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From time to time we meet the titles of news which impress us with its weirdness. Reading them we usually feel cognitive dissonance and delight at the same time. We collect these titles in one place. We do not claim the originality, relevance and the reliability of the information but each title has its own source..
        /// </summary>
        public static string AboutUsPopupText {
            get {
                return ResourceManager.GetString("AboutUsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string AboutUsPopupTitle {
            get {
                return ResourceManager.GetString("AboutUsPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE.
        /// </summary>
        public static string GoToSource {
            get {
                return ResourceManager.GetString("GoToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the link.
        /// </summary>
        public static string InsertTheLink {
            get {
                return ResourceManager.GetString("InsertTheLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link was copied to clipboard.
        /// </summary>
        public static string LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGEST.
        /// </summary>
        public static string Suggest {
            get {
                return ResourceManager.GetString("Suggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGEST NEWS.
        /// </summary>
        public static string SuggestNews {
            get {
                return ResourceManager.GetString("SuggestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your news successfully suggested.
        /// </summary>
        public static string YourNewsSuccessfullySuggested {
            get {
                return ResourceManager.GetString("YourNewsSuccessfullySuggested", resourceCulture);
            }
        }
    }
}
