//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbaNews.Resources.Web.Areas.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrontStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EbaNews.Resources.Web.Areas.Home.FrontStrings", typeof(FrontStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        /// </summary>
        public static string AboutUsPopupText {
            get {
                return ResourceManager.GetString("AboutUsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string AboutUsPopupTitle {
            get {
                return ResourceManager.GetString("AboutUsPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE.
        /// </summary>
        public static string GoToSource {
            get {
                return ResourceManager.GetString("GoToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the link.
        /// </summary>
        public static string InsertTheLink {
            get {
                return ResourceManager.GetString("InsertTheLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link was copied to clipboard.
        /// </summary>
        public static string LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGEST.
        /// </summary>
        public static string Suggest {
            get {
                return ResourceManager.GetString("Suggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGEST NEWS.
        /// </summary>
        public static string SuggestNews {
            get {
                return ResourceManager.GetString("SuggestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your news successfully suggested.
        /// </summary>
        public static string YourNewsSuccessfullySuggested {
            get {
                return ResourceManager.GetString("YourNewsSuccessfullySuggested", resourceCulture);
            }
        }
    }
}
