//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbaNews.Resources.Web.Areas.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EbaNews.Resources.Web.Areas.Home.LayoutStrings", typeof(LayoutStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUsFooter {
            get {
                return ResourceManager.GetString("AboutUsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you like the news?.
        /// </summary>
        public static string DidYouLikeTheNews {
            get {
                return ResourceManager.GetString("DidYouLikeTheNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Most Idiotic News Titles.
        /// </summary>
        public static string SiteMoto {
            get {
                return ResourceManager.GetString("SiteMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGEST NEWS.
        /// </summary>
        public static string SuggestNews {
            get {
                return ResourceManager.GetString("SuggestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram channel.
        /// </summary>
        public static string TelegramChannel {
            get {
                return ResourceManager.GetString("TelegramChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add yours!.
        /// </summary>
        public static string YouCanAddYour {
            get {
                return ResourceManager.GetString("YouCanAddYour", resourceCulture);
            }
        }
    }
}
